version: "3.1"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - db.env

  be-app:
    image: murmur/be-app
    restart: always
    ports:
      - 8000:80
    env_file:
      - be.env

  fe-app:
    image: murmur/fe-app
    restart: always
    ports:
      - 8888:80
