---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: {ECR_HOST}/murmur/backend-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-lb
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: backend-app
